### PR TITLE
MKL fix for mac

### PR DESCRIPTION
**Pull request by ajaypanyala**
macOS linker does not support `--{start,end}-group` 
The IntelMKL link line advisor also does not suggest these options when macOS is selected.

### CODE REVIEW

**Comment by ajaypanyala** [comment]
@wavefunction91 This PR is tested on an Intel MAC. MKL is obviously not supported on the new M1,M2 (Arm) macs. Should we just throw an error if a MAC is detected preventing MKL discovery completely  or allow discovery for intel based macs (maybe by checking the [processor](https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html)) ?

**Comment by wavefunction91** [comment]
By MacOS linker, do you mean `AppleClang`? Or is this some strange Mac specific thing that infects all compilers? We can definitely do a processor or OS check if it's the latter, compiler check if the former.

**Comment by ajaypanyala** [comment]
Since [GNU ld](https://linux.die.net/man/1/ld) is not supported on macOS, the default linker on macOS is used regardless of the compiler (am using brew installed gcc-12 in this case for testing). Added a check to detect `arm64` and report error.

**Comment by wavefunction91** [comment]
Adding a `FATAL_ERROR` on `arm64` would bring down the whole application - I'd just have it "try" to search for MKL, fail, and move on with its day. We could add an early exit condition if we're really concerned about MKL existing on ARM environments, but a failed check isn't a large overhead

**Comment by ajaypanyala** [comment]
Changed it to a warning.

**Pull request merged**
